language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy  # Needed by OpenFisca-Core (fails with pip install)
install:
  - pip install flake8
  - pip install -r requirements.txt
  - pip install -e .[introspection,tests]
script: make test
